kafka:
  brokers:
    - "redpanda:9092"
  group_id: "kafka-es-bulker"
  topics:
    - "topic-a"
    - "topic-b"

es:
  addresses:
    - "http://elasticsearch:9200"
  username: ""
  password: ""

mappings:
  topic-a: "index-a"
  topic-b: "index-b"

worker:
  num_workers: 4
  batch_size: 500
  batch_bytes: 5_000_000
  flush_interval_seconds: 2s
