services:
  # ---- Kafka broker (Redpanda) ----
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    networks:
      - localnet

  # ---- Kafka UI ----
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=redpanda:9092
    depends_on:
      - redpanda
    networks:
      - localnet

  # ---- Elasticsearch ----
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - localnet

  # ---- Kibana ----
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - localnet

  # ---- Kafka -> Elasticsearch Consumer ----
  consumer:
    build:
      context: .
      dockerfile: ./Dockerfile.consumer
    container_name: kafka-es-consumer
    depends_on:
      - redpanda
      - elasticsearch
    networks:
      - localnet

  # ---- Kafka Producer ----
  producer:
    build:
      context: .
      dockerfile: ./Dockerfile.producer
    container_name: kafka-producer
    depends_on:
      - redpanda
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
