FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o consumer ./cmd/service

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/consumer .
COPY config.yaml .
CMD ["./consumer"]
