FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o producer ./cmd/producer

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/producer .
COPY config.yaml .
CMD ["./producer"]
